// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlG7DIKEq0jv5UR6STjIAlBsB8D45bic4',
    appId: '1:712949385900:web:7894414f9e904934b96d09',
    messagingSenderId: '712949385900',
    projectId: 'calofit-c8c24',
    authDomain: 'calofit-c8c24.firebaseapp.com',
    storageBucket: 'calofit-c8c24.firebasestorage.app',
    measurementId: 'G-KHMLF3NZSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW0uNrX9SxWD11l1VxxkvZYElLg1rxx1E',
    appId: '1:712949385900:android:ea027ab73af1b001b96d09',
    messagingSenderId: '712949385900',
    projectId: 'calofit-c8c24',
    storageBucket: 'calofit-c8c24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA10jYXeX_HgZs9I0XSPHQXiag4NBpGcWU',
    appId: '1:712949385900:ios:18745568f3289819b96d09',
    messagingSenderId: '712949385900',
    projectId: 'calofit-c8c24',
    storageBucket: 'calofit-c8c24.firebasestorage.app',
    iosBundleId: 'com.example.calofitFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA10jYXeX_HgZs9I0XSPHQXiag4NBpGcWU',
    appId: '1:712949385900:ios:18745568f3289819b96d09',
    messagingSenderId: '712949385900',
    projectId: 'calofit-c8c24',
    storageBucket: 'calofit-c8c24.firebasestorage.app',
    iosBundleId: 'com.example.calofitFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlG7DIKEq0jv5UR6STjIAlBsB8D45bic4',
    appId: '1:712949385900:web:0d019f4fe1e007a7b96d09',
    messagingSenderId: '712949385900',
    projectId: 'calofit-c8c24',
    authDomain: 'calofit-c8c24.firebaseapp.com',
    storageBucket: 'calofit-c8c24.firebasestorage.app',
    measurementId: 'G-PPDEHGHYTK',
  );
}
